### ISSUE TITLE
[feature] 두번째 EC2서버 설정 및 mariadb replication

### ISSUE THREAD

**Issue by ghdic** [DevelopLife/reviewtwits_backend#104]
# 🛠 Issue
트래픽 분산을 위해 두번째 EC2 증설

# 📝 Todo
- [x] 두번째 EC2 세팅
- [x] nginx 로드밸런싱 설정
- [x] mariadb replication 설정
- [x] aws rds로 변경후 세팅
- [x] spring boot에서 master-slave구분해서 사용하도록 세팅
