### ISSUE TITLE
[refactor] 통계 관련 API 수정하기

### ISSUE THREAD

**Issue by WhalesBob** [DevelopLife/reviewtwits_backend#237]
# 🛠 Issue
프론트앤드 파트에서 수정 요청이 와서 수정 작업을 진행합니다.

# 📝 Todo
- [x] /project 에 존재하던 통계 관련 API 를 /statistics 로 이동
- [x] visited-info 의 출력 양식을 요청받은 대로 변경하기 
- [x] visit-graph-info 와 recent-visit-counts 의 양식을 통일하
