### ISSUE TITLE
[refactor] 프로젝트명 유니크성 및 url-pattern 점검 관련 작업

### ISSUE THREAD

**Issue by WhalesBob** [DevelopLife/reviewtwits_backend#257]
# 🛠 Issue
프로젝트명을 유니크 하게 설정하고, url-pattern 유효성 검증하는 로직을 분리하는 작업 수행하기

# 📝 Todo
- [x] 프로젝트 이름을 unique 하게 만들고, 영어와 숫자로만 처리할 수 있도록 바꾸기 
- [x] url-pattern 입력 검증 로직 추가하고, 패턴이 맞지 않으면 400 번대 에러 코드 보내줄 수 있도록 하기
- [x] url-pattern 검증 로직 분리하기
